[project]
name = "fashionmatch_ai___sprint_5_6_react_native_backend_development"
version = "0.1.0"
description = "fashionmatch_ai___sprint_5_6_react_native_backend_development using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[litellm,tools]==1.9.3",
]

[project.scripts]
fashionmatch_ai___sprint_5_6_react_native_backend_development = "fashionmatch_ai___sprint_5_6_react_native_backend_development.main:run"
run_crew = "fashionmatch_ai___sprint_5_6_react_native_backend_development.main:run"
train = "fashionmatch_ai___sprint_5_6_react_native_backend_development.main:train"
replay = "fashionmatch_ai___sprint_5_6_react_native_backend_development.main:replay"
test = "fashionmatch_ai___sprint_5_6_react_native_backend_development.main:test"
run_with_trigger = "fashionmatch_ai___sprint_5_6_react_native_backend_development.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
